/**
 * pack-specs — rewrite <target>/reference/specs.js as JSON.parse'd data.
 *
 * The spec catalogue compiles to a ~7k-line object-literal module whose
 * evaluation costs ~40 ms on EVERY `ib` invocation (measured, Node 24);
 * JSON.parse of the same data costs ~7 ms. tsc emits the literal form, then
 * this script (run by `npm run build` after tsc, and by check-dist-fresh
 * against its temp build so the byte-compare stays valid) replaces the module
 * body with JSON.parse of the evaluated value. Authoring stays in
 * src/reference/specs.ts — this transform is build-output-only, and the
 * packed module also drops specs.ts's co-located-spec import chains
 * (message daily/board, changelog, jerry) from the specs import path.
 *
 * Safety rails (each fails the build loudly):
 *  - the module must export exactly COMMAND_SPECS + COMMON_AUTH_ERRORS —
 *    a new runtime export in specs.ts must be added here deliberately;
 *  - both values must survive a JSON round-trip losslessly (no functions,
 *    undefined, non-finite numbers, or class instances).
 */
import { pathToFileURL } from "node:url";
import { writeFileSync, unlinkSync, existsSync, rmSync } from "node:fs";
import path from "node:path";

const targetDir = process.argv[2];
if (!targetDir) {
  console.error("usage: node scripts/pack-specs.mjs <dist-dir>");
  process.exit(1);
}

const specsPath = path.resolve(targetDir, "reference", "specs.js");
const mod = await import(pathToFileURL(specsPath).href);

const exportNames = Object.keys(mod).sort();
const expected = ["COMMAND_SPECS", "COMMON_AUTH_ERRORS"];
if (exportNames.join(",") !== expected.join(",")) {
  throw new Error(
    `pack-specs: reference/specs.js exports [${exportNames.join(", ")}], expected exactly ` +
      `[${expected.join(", ")}] — a new runtime export must be wired into scripts/pack-specs.mjs ` +
      `(only pure-JSON data can live in the packed module).`
  );
}

/** Reject any value JSON.stringify would alter or drop. */
function assertJsonSafe(value, at) {
  if (value === null) return;
  const t = typeof value;
  if (t === "string" || t === "boolean") return;
  if (t === "number") {
    if (!Number.isFinite(value)) throw new Error(`pack-specs: non-finite number at ${at}`);
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((v, i) => {
      if (v === undefined) throw new Error(`pack-specs: undefined array element at ${at}[${i}]`);
      assertJsonSafe(v, `${at}[${i}]`);
    });
    return;
  }
  if (t === "object") {
    const proto = Object.getPrototypeOf(value);
    if (proto !== Object.prototype && proto !== null) {
      throw new Error(`pack-specs: non-plain object at ${at}`);
    }
    for (const [k, v] of Object.entries(value)) {
      if (v === undefined) throw new Error(`pack-specs: undefined value at ${at}.${k}`);
      assertJsonSafe(v, `${at}.${k}`);
    }
    return;
  }
  throw new Error(`pack-specs: non-JSON value (${t}) at ${at}`);
}

assertJsonSafe(mod.COMMON_AUTH_ERRORS, "COMMON_AUTH_ERRORS");
assertJsonSafe(mod.COMMAND_SPECS, "COMMAND_SPECS");

const emit = (name, value) =>
  `export const ${name} = JSON.parse(${JSON.stringify(JSON.stringify(value))});\n`;

writeFileSync(
  specsPath,
  "// GENERATED by scripts/pack-specs.mjs from the tsc build of src/reference/specs.ts.\n" +
    "// Do not edit — author in src/reference/specs.ts; `npm run build` regenerates this.\n" +
    emit("COMMON_AUTH_ERRORS", mod.COMMON_AUTH_ERRORS) +
    emit("COMMAND_SPECS", mod.COMMAND_SPECS),
  "utf8"
);

const mapPath = `${specsPath}.map`;
if (existsSync(mapPath)) unlinkSync(mapPath);

// The packed specs.js no longer imports the per-domain segment modules
// (src/reference/specs/*.ts, fb#782) — their compiled output would ship ~600 KB
// of dead duplicate spec data in the committed dist, so prune the whole dir.
// check-dist-fresh runs this script against its temp build too, so the
// byte-compare sees identically pruned trees. An eslint no-restricted-imports
// rule keeps runtime code from importing a segment directly (it would vanish
// here).
rmSync(path.resolve(targetDir, "reference", "specs"), { recursive: true, force: true });

console.log(
  `pack-specs OK — ${path.join(targetDir, "reference/specs.js")} packed ` +
    `(${mod.COMMAND_SPECS.length} specs)`
);
