import type { CommandSpec } from "../../output/help.js";
import { FROM_JSON_BODY_FLAG } from "./shared.js";

export const BETOMIK_ORDERBOOK_SPECS: CommandSpec[] = [
  {
    command: "ib dev betomik-orderbook import",
    description: "Bulk-load a parsed Betomik order-book run into the staging table for review before any real sync (developer only).",
    tier: "developer",
    auth: "any",
    writeFlags: true,
    dryRunKind: "server",
    flags: [
      { name: "body", type: "json", required: true, description: "{ sheetLabel, isoYear, isoWeek, rows } — the parser's --json-out payload, forwarded verbatim" },
      FROM_JSON_BODY_FLAG,
    ],
    args: [],
    notes: [
      "The request body is read via --body/--from-json, NOT typed flags — it must be exactly {sheetLabel, isoYear, isoWeek, rows}, the shape parse-betomik-orderbook.py's --json-out writes.",
      "Each entry in rows is one job record from the parser's own output (source_type, plant_or_note, driver_name, etc.) — nothing here re-validates the parser's classification, it is stored as-is plus a server-side driver-name match.",
    ],
    outputShape: "{ importRunId, rowCount }",
    errors: [
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Only system admin/developer can trigger an import" },
      { http: 400, exit: 4, meaning: "Missing sheetLabel/isoYear/isoWeek/rows", remedy: "Pass a complete {sheetLabel, isoYear, isoWeek, rows} body" },
      { origin: "client", exit: 4, meaning: "No --body or --from-json payload given", remedy: "Pass --from-json <file|-> (the parser's json-out file) or --body '<json>'" },
    ],
    examples: [
      'ib dev betomik-orderbook import --from-json week40.json --reason "manual weekly import"',
    ],
  },
  {
    command: "ib dev betomik-orderbook runs",
    description: "List Betomik order-book import runs — sheet label, ISO year/week, row count, importedAt — newest first (GET /api/betomik-orderbook/runs). The week-selector for `rows`: pick the run whose isoYear/isoWeek match, latest importedAt if several.",
    tier: "developer",
    auth: "any",
    flags: [],
    args: [],
    outputShape: "ListEnvelope<{ importRunId, sheetLabel, isoYear, isoWeek, importedAt, importedBy, rowCount }>",
    errors: [
      { http: 403, exit: 3, meaning: "Not a system admin/developer and not an admin of the Betomik company", remedy: "Use a developer token, or an asiakasAdmin of asiakasId 27" },
    ],
    examples: ["ib dev betomik-orderbook runs"],
  },
  {
    command: "ib dev betomik-orderbook rows",
    description: "Staging rows of one import run (GET /api/betomik-orderbook/runs/:runId/rows) — jobDate, plate, vehicleLabel, driverName, driverMatchStatus, sourceType (betomik_self|third_party_plant|unspecified), plantOrNote, m3 (null when the sheet value was unparseable), reviewStatus. The read side of `import`; the weekly tenant report sums m3 and groups by plate from these rows.",
    tier: "developer",
    auth: "any",
    flags: [],
    args: [{ name: "runId", type: "number", description: "importRunId from `runs`" }],
    outputShape: "ListEnvelope<{ betomikOrderbookImportRowId, importRunId, jobDate, day, tableName, plate, vehicleLabel, vehicleId, vehicleNo, vehiclePuomi, vehicleRegNo, driverRaw, driverName, matchedPersonId, driverMatchStatus, tehdasTilaaja, sourceType, plantOrNote, sourceAsiakasId, betomikBuys, betomikCrew, plantSijaintiId, plantOwnerAsiakasId, plantResolved, customerGuess, siteText, siteClassification, rowKind: 'keikka'|'palkki', palkkiType, maybeNote, m3, aiJson, aiModel, aiProposedAt, reviewStatus, reviewedBy }>",
    notes: [
      "rowKind is the owner's rule applied at import (factory column non-empty => keikka; empty or 'Halli' => palkki) unless a human overrode it via `review`; palkkiType names one of the tenant's grid_palkkiTypes. aiJson is the AI proposer's stored proposal ({rowKind, palkkiType, customer, site, plant, drivers, confidence, reason} or {error}) — see `propose`/`ai-stats`.",
    ],
    errors: [
      { origin: "client", exit: 4, meaning: "runId is not a positive integer", remedy: "Pass the importRunId from `ib dev betomik-orderbook runs`" },
      { http: 400, exit: 4, meaning: "Backend rejected runId", remedy: "Pass a numeric importRunId" },
      { http: 403, exit: 3, meaning: "Not a system admin/developer and not an admin of the Betomik company", remedy: "Use a developer token, or an asiakasAdmin of asiakasId 27" },
    ],
    examples: ["ib dev betomik-orderbook rows 1"],
  },
  {
    command: "ib dev betomik-orderbook review",
    description: "Review one staging row by id (POST /api/betomik-orderbook/rows/:rowId/review): set reviewStatus and optionally override the keikka/palkki classification. The human's --row-kind/--palkki-type is the ground truth the AI proposer is measured against (`ai-stats`).",
    tier: "developer",
    auth: "any",
    writeFlags: true,
    dryRunKind: "server",
    flags: [
      { name: "status", type: "string", required: true, description: "pending | approved | rejected" },
      { name: "row-kind", type: "string", description: "keikka | palkki — override the parser's classification" },
      { name: "palkki-type", type: "string", description: "one of the tenant's active grid_palkkiTypes names (e.g. huolto, pois ajosta, kommentti); ignored/cleared when --row-kind keikka" },
      { name: "note", type: "string", description: "reviewNotes (kept when omitted)" },
    ],
    args: [{ name: "rowId", type: "number", description: "betomikOrderbookImportRowId from `rows`" }],
    outputShape: "{ updated: boolean } — updated:false means no row with that id under the Betomik tenant",
    errors: [
      { origin: "client", exit: 4, meaning: "rowId is not a positive integer", remedy: "Pass the betomikOrderbookImportRowId from `ib dev betomik-orderbook rows <runId>`" },
      { http: 400, exit: 4, meaning: "Bad status / rowKind / palkkiType", remedy: "status: pending|approved|rejected; rowKind: keikka|palkki; palkkiType must be one of the names the 400 message lists" },
      { http: 403, exit: 3, meaning: "Not a system admin/developer and not an admin of the Betomik company", remedy: "Use a developer token, or an asiakasAdmin of asiakasId 27" },
    ],
    examples: [
      'ib dev betomik-orderbook review 143 --status approved --row-kind palkki --palkki-type "pois ajosta" --reason "Halli-rivi, laivaan"',
      "ib dev betomik-orderbook review 8 --status approved --row-kind keikka --dry-run",
    ],
  },
  {
    command: "ib dev betomik-orderbook propose",
    description: "Run the AI proposer over one import run (POST /api/betomik-orderbook/runs/:runId/propose): an LLM sees ONLY each row's raw sheet cells and proposes {rowKind, palkkiType, customer, site, plant, drivers, confidence, reason}, stored in aiJson beside the deterministic parse. Proposals never change rowKind/palkkiType — a human does, via `review`. Skips rows that already carry a non-error proposal unless --force. Synchronous, ~2 min per 176-row week.",
    tier: "developer",
    auth: "any",
    writeFlags: true,
    dryRunKind: "server",
    flags: [
      { name: "provider", type: "string", description: "bedrock (Claude via AWS Bedrock EU, default) | local (OpenAI-compatible LAN server from AI_LOCAL_BASE_URL/AI_LOCAL_MODEL — the backend must be able to reach it)" },
      { name: "force", type: "boolean", description: "Re-propose every row, overwriting existing proposals" },
    ],
    args: [{ name: "runId", type: "number", description: "importRunId from `runs`" }],
    outputShape: "{ runId, provider, model, proposed, failed, skipped, sampleError } — per-row failures are stored as aiJson {error} and counted in failed; --dry-run returns { dryRun:true, wouldPropose:{ runId, provider, rows, skipped } }",
    errors: [
      { origin: "client", exit: 4, meaning: "runId is not a positive integer", remedy: "Pass the importRunId from `ib dev betomik-orderbook runs`" },
      { http: 400, exit: 4, meaning: "Unknown provider, or the provider is not configured (AI_BEDROCK_MODEL / AI_LOCAL_BASE_URL)", remedy: "Use --provider bedrock|local and configure the backend's env for it" },
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Only system admin/developer can run the proposer" },
      { http: 500, exit: 1, meaning: "The FIRST row failed (bad model id, missing AWS credentials, unreachable local server) — nothing was stored", remedy: "Fix the provider configuration and re-run; later rows fail individually into aiJson {error} instead" },
    ],
    examples: [
      "ib dev betomik-orderbook propose 1 --dry-run",
      'ib dev betomik-orderbook propose 1 --provider bedrock --reason "week 37 proposals"',
      "ib --endpoint http://127.0.0.1:3000 dev betomik-orderbook propose 1 --provider local --force",
    ],
  },
  {
    command: "ib dev betomik-orderbook ai-stats",
    description: "Agreement of stored AI proposals with the human-APPROVED rows of one run (GET /api/betomik-orderbook/runs/:runId/ai-stats). humanAgreement (rowKind, palkkiType) is the only true accuracy figure; parserAgreement (customer/site/plant/drivers) compares the AI to the deterministic parser, a triage signal, not accuracy. byConfidence buckets rowKind agreement at confidence >= 0.7/0.8/0.9 — the input to an auto-approve threshold decision.",
    tier: "developer",
    auth: "any",
    flags: [],
    args: [{ name: "runId", type: "number", description: "importRunId from `runs`" }],
    outputShape: "{ runId, models, proposed, errored, scored, humanAgreement: { rowKind: {n,agree,rate}, palkkiType }, parserAgreement: { customer, site, plant, drivers }, byConfidence: [{ min, n, agree, rate }], note }",
    errors: [
      { origin: "client", exit: 4, meaning: "runId is not a positive integer", remedy: "Pass the importRunId from `ib dev betomik-orderbook runs`" },
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Use a developer token" },
    ],
    examples: ["ib dev betomik-orderbook ai-stats 1"],
  },
  {
    command: "ib dev betomik-orderbook sync",
    description: "Sync a Betomik order-book payload straight into keikka/palkki rows (POST /api/betomik-orderbook/sync): shadow (default) computes without writing, create only inserts new rows, full also updates/closes existing ones. Body is --body/--from-json (the same {sheetLabel, isoYear, isoWeek, rows} shape `import` takes) with --mode/--provider/--digest merged in.",
    tier: "developer",
    auth: "any",
    writeFlags: true,
    dryRunKind: "server",
    flags: [
      { name: "body", type: "json", required: true, description: "{ sheetLabel, isoYear, isoWeek, rows } — same shape as `import`" },
      FROM_JSON_BODY_FLAG,
      { name: "mode", type: "string", description: "shadow (default) | create | full" },
      { name: "provider", type: "string", description: "bedrock (default) | local — only relevant for rows still needing AI cell extraction" },
      { name: "digest", type: "boolean", description: "Send the daily digest e-mail to the owner after the sync and stamp the included audit rows as digested — a real side effect, not a response field" },
    ],
    args: [],
    notes: [
      "--dry-run suppresses the keikka/palkki writes and the auto-creates, NOT the ledger: syncStatus/plannedAction/blockReason are still written for every row.",
      "A dry run WITH --provider still performs (and pays for) the AI cell extractions and stores extractedJson — --dry-run is about entity writes, not about the model calls.",
      "--digest SENDS MAIL to the owner and marks the audit rows it listed as digested; it is not a response-only summary and a dry run does not suppress it.",
    ],
    outputShape: "{ upsert: { importRunId, inserted, updated, unchanged, gone }, summary: { importRunId, mode, dryRun, rows, planned, written, blocked, extracted, errors }, digest } — --dry-run returns { dryRun: true, wouldSync: { isoYear, isoWeek, rows, mode, provider }, validation }",
    errors: [
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Only system admin/developer can trigger a sync" },
      { http: 400, exit: 4, meaning: "Missing sheetLabel/isoYear/isoWeek/rows, unknown mode/provider, provider not configured (AI_BEDROCK_* / AI_LOCAL_*), or more than 40 rows without `extracted` for the chosen provider", remedy: "Pass the parser's full payload; use --mode shadow|create|full and --provider bedrock|local; run scripts/sales/betomik-orderbook-extract.py first when rows lack extracted" },
      { origin: "client", exit: 4, meaning: "No --body or --from-json payload given", remedy: "Pass --from-json <file|-> or --body '<json>'" },
    ],
    examples: [
      'ib dev betomik-orderbook sync --from-json rows.json --mode shadow --reason "cron tick"',
    ],
  },
  {
    command: "ib dev betomik-orderbook resync",
    description: "Re-run sync for an already-imported run (POST /api/betomik-orderbook/runs/:runId/sync) without re-importing rows — for re-syncing after a review pass or a mode change.",
    tier: "developer",
    auth: "any",
    writeFlags: true,
    dryRunKind: "server",
    flags: [
      { name: "mode", type: "string", description: "shadow (default) | create | full" },
      { name: "provider", type: "string", description: "bedrock (default) | local — only relevant for rows still needing AI cell extraction" },
    ],
    args: [{ name: "runId", type: "number", description: "importRunId from `runs`" }],
    notes: [
      "--dry-run STILL WRITES LEDGER STATE (syncStatus/plannedAction/blockReason) for every row — only the keikka/palkki writes and the auto-creates are suppressed.",
      "A dry run WITH --provider still performs (and pays for) the AI cell extractions and stores extractedJson.",
    ],
    outputShape: "{ summary: { importRunId, mode, dryRun, rows, planned, written, blocked, extracted, errors } } — --dry-run returns { dryRun: true, summary }",
    errors: [
      { origin: "client", exit: 4, meaning: "runId is not a positive integer", remedy: "Pass the importRunId from `ib dev betomik-orderbook runs`" },
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Only system admin/developer can trigger a sync" },
      { http: 400, exit: 4, meaning: "Unknown mode/provider, or the chosen provider has more than 40 un-extracted rows", remedy: "Use --mode shadow|create|full, --provider bedrock|local, and extract cells in smaller batches first" },
    ],
    examples: ["ib dev betomik-orderbook resync 5 --mode full --dry-run"],
  },
  {
    command: "ib dev betomik-orderbook extract-prompt",
    description: "The AI cell-extraction prompt template (GET /api/betomik-orderbook/extract-prompt) — the system prompt, schema and tool name a sync run's provider uses to pull structured fields out of raw sheet cells. Read-only; mainly for debugging what the extractor is actually asked to do.",
    tier: "developer",
    auth: "any",
    flags: [],
    args: [],
    outputShape: "{ system, schema, cells, toolName }",
    errors: [
      { http: 403, exit: 3, meaning: "Not a system admin or developer", remedy: "Use a developer token" },
    ],
    examples: ["ib dev betomik-orderbook extract-prompt"],
  },
  {
    command: "ib dev betomik-orderbook exceptions",
    description: "Blocked/exception rows from one sync run (GET /api/betomik-orderbook/runs/:runId/exceptions) — rows `sync`/`resync` could not write (unresolved customer/site/plant, ambiguous driver, etc.), for a human to resolve via `review` before the next resync.",
    tier: "developer",
    auth: "any",
    flags: [],
    args: [{ name: "runId", type: "number", description: "importRunId from `runs`" }],
    outputShape: "ListEnvelope<{ betomikOrderbookImportRowId, jobDate, plate, driverName, customerGuess, siteText, rowKind, syncStatus, plannedAction, blockReason, keikkaId, palkkiId }> — syncStatus is always 'blocked'; frozen/synced/removed rows are never returned",
    prettyColumns: ["betomikOrderbookImportRowId", "jobDate", "plate", "customerGuess", "syncStatus", "plannedAction", "blockReason"],
    errors: [
      { origin: "client", exit: 4, meaning: "runId is not a positive integer", remedy: "Pass the importRunId from `ib dev betomik-orderbook runs`" },
      { http: 403, exit: 3, meaning: "Not a system admin/developer and not an admin of the Betomik company", remedy: "Use a developer token, or an asiakasAdmin of asiakasId 27" },
    ],
    examples: ["ib dev betomik-orderbook exceptions 5"],
  },
  {
    command: "ib dev betomik-orderbook audit",
    description: "Entities the sync AUTO-CREATED (customers, worksites, contact persons) — one row each; `digestedAt` = already included in a sent digest (GET /api/betomik-orderbook/audit), newest first; --since narrows to entities created at/after that ISO timestamp.",
    tier: "developer",
    auth: "any",
    flags: [{ name: "since", type: "string", description: "ISO timestamp — only rows created at/after it" }],
    args: [],
    outputShape: "ListEnvelope<{ auditId, importRowId, entity: 'asiakas'|'tyomaa'|'person', entityId, label, createdAt, digestedAt }>",
    errors: [
      { http: 403, exit: 3, meaning: "Not a system admin/developer and not an admin of the Betomik company", remedy: "Use a developer token, or an asiakasAdmin of asiakasId 27" },
    ],
    examples: ["ib dev betomik-orderbook audit --since 2026-09-01"],
  },
];
